// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebxwvoepyxierzhmthdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVieHd2b2VweXhpZXJ6aG10aGRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NTE5NDcsImV4cCI6MjA1NTUyNzk0N30.oVvwYEH9vwI3SlBfJ68EJN830l83fm42DbHrFzmLS7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);